blank_issues_enabled: true
contact_links:
  - name: ðŸ’¡ New Idea
    url: https://github.com/aivascu/AutoFixture.Community.AutoMapper/discussions/categories/ideas
    about: Propose and discuss ideas and proposals
  - name: ðŸ¤” Question
    url: https://github.com/aivascu/AutoFixture.Community.AutoMapper/discussions/categories/q-a
    about: Ask a questions or seek help
  - name: ðŸ“ˆ Show and Tell
    url: https://github.com/aivascu/AutoFixture.Community.AutoMapper/discussions/categories/show-and-tell
    about: Share something cool (e.g. snippets, success stories, etc.)